insert into Country (name, code_name) values ('Australia', 'AU');
insert into Country (name, code_name) values ('Canada', 'CA');
insert into Country (name, code_name) values ('France', 'FR');
insert into Country (name, code_name) values ('Hong Kong', 'HK');
insert into Country (name, code_name) values ('Iceland', 'IC');
insert into Country (name, code_name) values ('Japan', 'JP');
insert into Country (name, code_name) values ('Nepal', 'NP');
insert into Country (name, code_name) values ('Russian Federation', 'RU');
insert into Country (name, code_name) values ('Sweden', 'SE');
insert into Country (name, code_name) values ('Switzerland', 'CH');
insert into Country (name, code_name) values ('United Kingdom', 'GB');
insert into Country (name, code_name) values ('United States', 'US');